pipeline {
    agent any
    tools {
        maven 'Maven 3.9.2'
    }
    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                    sh 'mvn clean package'
            }
        }
        stage('Test') {
            steps {
                    sh 'mvn test'
            }
        }
        stage('Deploy') {
            steps {
                    sh 'mvn deploy'
            }
        }
    }
}
