pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                sh 'javac src/main/java/com/techprimers/testing/FizzBuzz.java -d target'
            }
        }
        stage('Test') {
            steps {
                sh 'java -cp target com.techprimers.testing.FizzBuzzTest'
            }
        }
    }
}
